## Numpy 복습
* Numpy 패키지/ 라이브러리
* 배열(Array) <=> 리스트(List)
* 리스트: 파이썬 기본 자료형
    * 여러개의(0개 이상)데이터들을 묶어서 표현
    * 인덱스(위치 주소값), 호출+ 슬라이싱(리스트의 부분 집합)
    * 속도와 메모리의 효율성이 떨어짐
    * 길이가 가변적이고 원소 넣는 타입이 고정적이지 않음
* 배열(Array, ndarray)
    * 길이가 고정적이고 원소 타입도 고정(만들때 선언을 통해 고정한다!)

In [1]:
#pip install numpy
#!pip install numpy # 터미널 기능 호출
import numpy as np # numpy를 약어로 np로 사용하기 위해 as를 사용

## 1차원 배열
1. 축이 1개인 배열로 리스트나 튜플처럼 한줄로 이루어져 있음
2. np.array([...]) # 한줄짜리 리스트
    np.array([1,2,3,4,5])

## 백터화 연산
1. 리스트는 연산이 안됨 (리스트에서 +(더하기)는 리스트의 개수가 증가)
    a+1 리스트에서 덧셈은 같은 리스트끼리만 가능
    리스트에서의 덧셈은 같은 리스트만 가능하고, 그것은 '연결'을 의미함
    리스트에서의 곱셈은 정수만 가능하고, 해당 리스트를 n 배 반복하겠음
    즉, 벡터화 연산은 리스트에서 할 수 없다.
    
2. <b>`배열은 원소의 연산이 가능하다`<b>
    사칙(산술) 연산 가능, 논리연산, 비교연산 등 가능

## 2차원 배열
가로줄: 행(row)
세로줄: 열(column)
np.array([[...] ... ]) #리스트의 리스트
같은 열의 수!

## 3차원 배열
np.array([[[...]...] ... ]) #리스트의 리스트의 리스트

## 배열의 차원과 크기

arr.ndim  차원의 수 ex) 1,2,3 ...
shape  배열의 모양 ex) (3,),(2,3), (2,3,4) ...

## 중간정리
|배열|사용법|메소드or속성|비고|
|-|-|-|-|
|배열의 생성|np.array(data)|메소드|data: 배열로 만들어주려는 리스트|
|배열의 차원 수|arr.ndim|속성||
|배열의 모양|arr.shape|속성||

np = numpy<br>
arr = numpy로 만들어진 ndarray객체(배열)

## 배열의 인덱싱과 슬라이싱
1. index + ing -> 인덱스를 사용해서 특정 위치의 값을 호출해주거나 해당 위치에 값을 넣음

In [2]:
a = [1, 2, 3, 4, 5] # idx : 0 ~ 4
a[2] # a => 3을 가져오고 싶다
a[-3] # 뒤에서 3번째 

3

일차원 배열 인덱싱

In [3]:
a = np.array([0, 1, 2, 3, 4])
a[2], a[-1] # (2, 4)

(2, 4)

이차원 배열 인덱싱
- `,` (콤마) : 위치에 접근
- 차원 = 축 -> 콤마로 한다 / 그래프의 x축, y축

||0행|1열|2열|3열|
|-|-|-|-|-|
|0행|(0,0)|(0,1)|(0,2)|(0,3)|
|1행|(1,0)|(1,1)|(1,2)|(1,3)|
|2행|(2,0)|(2,1)|(2,2)|(2,3)|
|3행|(3,1)|(3,2)|(3,3)|(3,4)|

In [5]:
#             0열 1열 2열
b = np.array([[0, 1, 2], # 0행
              [3, 4, 5]]) # 1행
b[0, 0] # 첫(0)번째 행의 첫(0)번째 열

5

In [6]:
b[0, 1] # 첫번째 행의 두번째 열

1

In [7]:
b[-1, -1] # 마지막 행의 마지막 열

5

## 배열의 복사
1. 얕은 복사
    np.view()는 얕은 복사를 하는 메소드, 연결된 관계가 유지되어서 생기는 문제(데이터가 아닌 주소를 가르켜서 생기는 문제)
2. 깊은 복사
    np.copy()는 깊은 복사를 하는 메소드, 연결된 관계를 끊는 복사

## 슬라이싱
1. 부분 집합 -> 인데스들을 범위로 사용함

In [11]:

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

a[0, :] # 첫번째 행 전체 (: = 콜론, 전체)
# array([0, 1, 2, 3])
# 연습문제 다시 풀어보기

array([0, 1, 2, 3])

## 배열 인덱싱
* 배열의 인덱싱 != 배열의 배열의 인덱싱(1차원 배열의 인덱싱과 2차원배열의 인덱싱이 다른다?????????)
* 인덱싱을 할때 정수값을 넣는다 -> 대신에 배열(bool, 정수 인덱스) -> 인덱싱

    arr[idx] = [...] # 필터링, 스크리닝 -> 검색<br>
    idx는 bool (참/거짓) 또는 정수 인덱스로 이루어진 배열

#### 불리언 배열 인덱싱 : 원본 배열과 동일한 크기의 bool로 이루어진 배열 <br>
    → True 남기고, False는 지워줌
   벡터화 연산 → 비교연산, 논리연산 → 불리언 배열 → [] 넣으면? → 필터링 
#### 정수 배열 인덱싱 → 배열 안의 값은 정수 라벨(인덱스) → 호출을 해서 그것들로 부분집합
    정수 인덱스는 1번 ‘이상’ 호출이 가능하다
#### 배열의 검색 - 알면 좋다

## 배열의 인덱싱과 슬라이싱
||0행|
|-|-|
|콤마 ,|사용하자 하는 차원을 구분|
|콜론 :|전체 범위를 의미, 앞 뒤에 인덱스를 넣어서 특정 범위로 한정|
|arr[bool_arr] 불리언 배열 인덱싱|True만 남기도 False는 생략해주겠다 → 필터링|
|arr.copy()|깊은 복사가 가능 (메소드)|

##  배열의 생성과 변형
### 자료형
1. data-type
2. 배열은 통일된 자료형을 가진다.

    arr.dtype # 배열의 자료형
    o, i, f정도 사용

|dtype 접두사|설명|사용 예|
|-|-|-|
|`b`|불리언|`b` (참 혹은 거짓)|
|`i`|정수|`i8` (64비트)|
|`u`|부호 없는 정수|`u8` (64비트)|
|`f`|부동소수점|`f8` (64비트)|
|`c`|복소 부동소수점|`c16` (128비트)|
|`O`|객체|`0` (객체에 대한 포인터)|
|`S`|바이트 문자열|`S24` (24 글자)|
|`U`|유니코드 문자열|`U24` (24 유니코드 글자)|

### Inf(무한)  NaN(not a number)
* Inf: 무한대(infinity) -inf도 가능!
* nan: 숫자가 아니다 = 정의할 수 없는 숫자 = 계산을 할 수 없다
cf. 데이터베이스 null과 다름 - nan은 계산 불가임

### 배열 생성
* `np.array(리스트)`
*  `np.zeros(n)` # n의 크기를 가진 배열에 0으로 채움 ex) 덧셈 누적 등

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

*  `np.ones(n)` # n의 크기를 가진 배열에 1으로 채움 ex) 곱하기 등

In [14]:
np.ones((2,3,4),dtype='i8')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

`np.empty(배열의 모양)` 모양만 잡을때 사용

In [15]:
np.empty((4,3))

array([[1.40585611e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.14587773e-312, 5.69747499e-038],
       [1.51872253e-047, 1.19028781e-047, 3.21940698e-057],
       [5.64928291e-038, 2.31786463e-052, 4.04553373e-037]])

`np.arrange(...)`
파이썬의 range 함수와 유사

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 21, 2) # 시작(포함), 끝(제외), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

`np.linspace(...)`
1. 특정한 선형구간을 지정한 구간의 수만큼 분할
2. 직선 구간 -> 그래프 그릴때 사용

In [18]:
np.linspace(0, 100, 5) # 시작(포함), 끝(포함), 구간수

array([  0.,  25.,  50.,  75., 100.])

# 배열의 변형
전치연산(transpose)
  * 2차원 배열에서 행과 열을 바꾸는 작업
  * 배열의 `t`  속성
  arr.T # 2차원 행렬 

In [19]:
A = np.array([[1,2,3],[4,5,6]])
A, A.shape # 2 x 3

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [20]:
A.T, A.T.shape

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 (3, 2))

## 배열의 크기 변형(reshape)

In [21]:
a = np.arange(12) # 1차원 배열
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
b = a.reshape(3, 4) # 행이 3개 열이 4개로
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

####  -1 : 전체의 원소 수 -> 2차원 1, 3차원 2 -> 1개 -> 연산

In [23]:
a.reshape(3, -1) # 12 (12개를 3행으로 넣으려면 4열이 필요하지만 -1로 대신 가능)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a.reshape(-1, 4) # (12개를 4열로 넣으려면 3행이 필요하지만 -1로 대신 표현가능)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 배열 평탄화(flatten, revel)
* 2차원 이상의 다차원 배열을 1차원 배열로 변환(평평하게 만들어준다.)

### 배열의 크기 변형과 평탄화를 반대라고 이해만 해보자(이해를 위해서)

In [25]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 같은 배열에 대해 차원만 1차원 증가(newaxis)

In [27]:
x = np.arange(5) # 1차원 배열의 원소
x

array([0, 1, 2, 3, 4])

In [28]:
x[:, np.newaxis] # 2차원 배열로 만들어짐

array([[0],
       [1],
       [2],
       [3],
       [4]])