In [ ]:
import numpy as np # numpy를 사용하기 위해서 import를 사용

## 배열 연결
* 행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여 더 큰 배열을 생성

### concatenate


In [ ]:
"1" +"1" # 문자열이기때문에 결과는 11이다.

'11'

In [ ]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [ ]:
#벡터화 연산 (리스트처럼 concatnate 불가 - 리스트1 + 리스트2 = 리스트1 리스트2 로 보임)
arr1 = np.arange(1,4) # [1,2,3]
arr2 = np.arange(4,7) # [4,5,6]
arr1+arr2             # [4,7,9]

array([5, 7, 9])

In [ ]:
arr = np.concatenate([arr1, arr2]) # concatnate는 기능이 많다! 
arr # 1차원 배열 연결

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 2차원 배열
arr1 = np.arange(1,5).reshape(2,2) # arr1 [[1,2,],[3,4]] 2행 2열 배열로 변형(위에서 이미 arr1 선언해서)
arr2 = np.arange(5,9).reshape(2,2) # arr2 [[5,6],[7,8]] 2행 2열 배열로 변형(위에서 이미 arr2 선언해서)

In [ ]:
arr1 # 2차원 배열 출력

array([[1, 2],
       [3, 4]])

In [ ]:
arr2 # 2차원 배열 출력

array([[5, 6],
       [7, 8]])

In [ ]:
arr = np.concatenate([arr1, arr2]) # 열을 기준으로 합침(arr1 뒤에 arr2 붙은 형태)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr = np.concatenate([arr1, arr2], axis=0) # 열을 기준으로 합침 - 같은 열끼리
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr = np.concatenate([arr1, arr2], axis=1) # 행을 기준으로 정리 - 같은 행끼리 묶음 (0행끼리 한줄, 1행끼리 한줄)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
arr = np.concatenate([arr1, arr2], axis=2) # 일부로 오류 발생시키기
arr

AxisError: ignored

**h**orizontal 수평: 가로<br>
**v**ertical 수직: 세로

### `hstack`
* `행의 수가 같은` 두 개 이상의 배열을 **옆**으로 연결하여 열의 개수가 늘어난 배열을 만듦
* 연결할 배열은 하나의 리스트(튜플)에 담아서 메소드에 넣어줘야함
* 가로로 결합

In [ ]:
a1 = np.ones((2,3))# 2행 3열 
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a2 = np.zeros((2,2)) # 2행 2열
a2

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.hstack([a1,a2]) # 행의 숫자가 같아서 가능, 같은 행에 추가 되는 형태로 보임

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [ ]:
np.hstack((a1,a2)) # 튜플 형태로 넣어도 동일

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

### `vstack`
* `열의 수가 같은` 두 개 이상의 배열을 **위아래**으로 연결하여 행의 개수가 늘어난 배열을 만듦
* 연결할 배열은 하나의 리스트(튜플)에 담아서 메소드에 넣어줘야 함
* 세로로 결합

In [ ]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
b1, b2

(array([[1., 1., 1.],
        [1., 1., 1.]]), array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [ ]:
np.vstack([b1, b2]) # 행이 쌓이는 것을 볼 수 있다. - 열이 같은 형태이고 행이 추가 됨

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 'dstack' depth
* 제3의 축 즉, 행이나 열이 아니라 깊이(depth) 방향으로 배열 합침
* 가장 안쪽의 원소 차원이 증가, 즉 가장 내부의 숫자원소가 배열
* 깊이 방향으로 결합

In [ ]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))

In [ ]:
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.dstack([c1,c2]) # 행과 열 둘다 증가 된다 # 리스트 속에 리스트
# 한 행의 각 열을 행으로 만들어 다른 리스트와 합쳐서. 리스트 속에 리스트로 만들어졌구나
# 같은 행과 열의 위치에 있던 것끼리 붙였다.

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

### `stack`
* `dstack`의 기능을 확장한 것으로 `dstack`처럼 마지막 차원으로 연결하는 것이 아니라 사용자가 지정한 차원(축으로) 배열을 연결
* axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정함
* 디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성. 즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 함

In [ ]:
c = np.stack([c1, c2]) # axis = 0 # vstack과 같은 결과
c, c.shape 

(array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]), (2, 3, 4))

In [ ]:
c = np.stack([c1, c2], axis=1) # axis = 1 # hstack과 같은 결과
c, c.shape 

(array([[[1., 1., 1., 1.],
         [0., 0., 0., 0.]],
 
        [[1., 1., 1., 1.],
         [0., 0., 0., 0.]],
 
        [[1., 1., 1., 1.],
         [0., 0., 0., 0.]]]), (3, 2, 4))

In [ ]:
c = np.stack([c1, c2], axis=2) # axis = 2 # dstack과 같은 결과
c, c.shape 

(array([[[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]]]), (3, 4, 2))

## axis는 결합할 축을 결정하는 것이다.
- 두 번째에 인수 axis에 결합할 축(차원)을 0부터 시작하는 것으로 지정하는 것은 numpy.concatenate()와 동일하다. 
- 그러나, axis는 결합된 배열을 위한 축을 지정한다.
- axis = 0로 지정하면 배열의 0차원째(행)에 따라 결합된다.
- axis = 1로 지정하면 2번째의 축(1차원째)이 열이므로 가로로 결합된다.
- 존재하지 않는 축(차원)을 지정하면 에러가 발생한다. 
- 결합 축 이외의 축의 사이즈가 일치하지 않고 있으면 에러가 된다
- -1은 가장 큰 수와 같다!!!

### `r_`
* `hstack` 비슷하게 배열을 좌-우 연결
* 메소드 소괄호(parenthesis, `()`)를 사용하지 않고, 대괄호(bracket, [])를 사용
* 특수 메소드 = 인덱서(indexer)

In [ ]:
np.r_[np.arange(1,2), np.arange(4,7)]

array([1, 4, 5, 6])

### `c_`
* 배열의 차원을 증가시킨 뒤 좌우로 연결

In [ ]:
np.c_[np.arange(1,4), np.arange(4,7)]

array([[1, 4],
       [2, 5],
       [3, 6]])

### `tile`
* 동일한 배열을 반복하여 연결

In [ ]:
a = np.arange(6).reshape(2, -1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.tile(a,2) #반복할 배열, 반복할 횟수(가로로 2번 )

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
np.tile(a, (3, 2)) # 행으로 3번, 열로 2번

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

## ⚓ 연습문제 1
array([[  0.,   0.,   0.,   1.,   1.],<br>
       [  0.,   0.,   0.,   1.,   1.],<br>
       [  0.,   0.,   0.,   1.,   1.],<br>
       [ 10.,  20.,  30.,  40.,  50.],<br>
       [ 60.,  70.,  80.,  90., 100.],<br>
       [110., 120., 130., 140., 150.],<br>
       [  0.,   0.,   0.,   1.,   1.],<br>
       [  0.,   0.,   0.,   1.,   1.],<br>
       [  0.,   0.,   0.,   1.,   1.],<br>
       [ 10.,  20.,  30.,  40.,  50.],<br>
       [ 60.,  70.,  80.,  90., 100.],<br>
       [110., 120., 130., 140., 150.]])

In [ ]:
arr1 = np.zeros((3,3))
arr2 = np.ones((3,2))
arr3 = np.arange(1,6).reshape(1,5)
arr4 = np.arange(6,11).reshape(1,5)
arr5 = np.arange(11,16).reshape(1,5)
arr1, arr2, arr3, arr4, arr5

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), array([[1., 1.],
        [1., 1.],
        [1., 1.]]), array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]))

In [ ]:
arr3 =arr3*10
arr4 =arr4* 10
arr5 =arr5*10

In [ ]:
# arr1과 arr2 합치기
arrays = np.hstack([arr1, arr2])
arrays

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [ ]:
arrays = np.vstack([arrays, arr3, arr4, arr5])

In [ ]:
arrays   # 2차원 배열을 1차원 배열로 만듦;;;; 다시하기

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [ ]:
arr1 = np.zeros((3,3))
arr2 = np.ones((3,2))
arr3 = np.arange(1,6).reshape(1,5)
arr4 = np.arange(6,11).reshape(1,5)
arr5 = np.arange(11,16).reshape(1,5)
arr3 =arr3*10
arr4 =arr4* 10
arr5 =arr5*10

In [ ]:
arrays1 = np.hstack([arr1, arr2])
arrays2 = np.hstack([arr_1, arr_2])

In [ ]:
arrays3 = np.vstack([arrays1, arr3, arr4, arr5])
arrays3

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [ ]:
arrays = np.stack([arrays3, arrays3])

In [ ]:
arrays

array([[[  0.,   0.,   0.,   1.,   1.],
        [  0.,   0.,   0.,   1.,   1.],
        [  0.,   0.,   0.,   1.,   1.],
        [ 10.,  20.,  30.,  40.,  50.],
        [ 60.,  70.,  80.,  90., 100.],
        [110., 120., 130., 140., 150.]],

       [[  0.,   0.,   0.,   1.,   1.],
        [  0.,   0.,   0.,   1.,   1.],
        [  0.,   0.,   0.,   1.,   1.],
        [ 10.,  20.,  30.,  40.,  50.],
        [ 60.,  70.,  80.,  90., 100.],
        [110., 120., 130., 140., 150.]]])

In [ ]:
# 강사님께서 만드신 방법

In [ ]:
# 0, 0, 0, 1, 1
a = np.zeros(3, dtype='f')
a

array([0., 0., 0.], dtype=float32)

In [ ]:
b = np.ones(2, dtype='f')

In [ ]:
# c = np.r_[a, b]
c = np.hstack([a, b])
c

array([0., 0., 0., 1., 1.], dtype=float32)

In [ ]:
d = np.tile(c, (3, 1))
d

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]], dtype=float32)

In [ ]:
e = np.arange(10, 160, 10, dtype='f')
e

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150.], dtype=float32)

In [ ]:
f = e.reshape(3, -1)
f

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

## 배열 분활

In [ ]:
arr = np.arange(1, 7)
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
arr = np.arange(1, 13).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
newarr = np.array_split(arr, 3, axis=1) # 열방향으로 분활
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]]), array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [ ]:
np.hsplit(arr,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]]), array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [ ]:
# np.hsplit(arr, n), np.vsplit(arr, n), np.dsplit(arr, 3) -> 쪼개줄 방향 / 몇개 쪼갤지

In [ ]:
np.vsplit(arr,3)

ValueError: ignored

In [ ]:
np.dsplit(arr,3)

ValueError: ignored

## 2차원 그리드 포인트 생성
* 변수가 2개인 2차원 함수 (x, y) 그래프를 그리거나 표를 작성하거나 할 때 2개의 좌표값 쌍 -> **grid point** (그리드포인트) -> 각 좌표에 대한 함수 값을 계산해야함
<br>
$
(x, y) = (0,0),(0,1),(0,2),(0,3),(0,4),(1,0),\cdots(2,4)
$

* `meshgrid` : 사각형 영역을 구성하는 가로축의 점들과 세로축의 점들을 나타내는 두 벡터를 인수로 받아서 이 사각형 영역을 이루는 조합 출력
=> x,y 좌표쌍들을 출력
* 결과 : 그리드 포인트의 x값만을 표시하는 행렬과 y갑

In [ ]:
x = np.arange(3)
x

array([0, 1, 2])

In [ ]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [ ]:
X, Y = np.meshgrid(x,y)

In [ ]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [ ]:
for x, y in zip(X, Y):
  print(list(zip(x,y)))

[(0, 0), (1, 0), (2, 0)]
[(0, 1), (1, 1), (2, 1)]
[(0, 2), (1, 2), (2, 2)]
[(0, 3), (1, 3), (2, 3)]
[(0, 4), (1, 4), (2, 4)]


In [ ]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]